### ISSUE TITLE
Please add GPL header to files

### ISSUE THREAD

**Issue by mattl** [creativecommons/new-www-plugin#1]
<one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

**Comment by fmann** [comment]
Copyright line and license terms added to the primary file of each plugin.
