### ISSUE TITLE
GF Donation Forms Require state/province for every country, but some countries don't have

### ISSUE THREAD

**Issue by ageeroms** [creativecommons/new-www-plugin#2]
On https://staging.creativecommons.org/donate/#gf_3 , state and province is a required field; some countries don't have a state/province. Can we make state optional, when not in the US, while still insisting on collecting the rest of the fields? An example of a country without any states is Isle of Man

**Comment by mattl** [comment]
Also double check the list of countries as it's different from what Civi
has. Mapping them over might be tricky.

**Comment by fmann** [comment]
There is a custom validation routine now that only requires State/Province for US and Canada. All others can pass through without it.

**Comment by fmann** [comment]
Closing this ticket because I believe the validation issue has been addressed.  Moving the issue that Matt brought up, mismatched countries, to a new ticket. #3.
